version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: kobi
      POSTGRES_PASSWORD: kobi
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kobi -d test"]
      interval: 5s
      timeout: 3s
      retries: 10
    # volumes:
    #   - ./postgres/init:/docker-entrypoint-initdb.d

  trino:
    image: trinodb/trino:443
    container_name: trino
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
